### ISSUE TITLE
The file tree should color filenames based on VCS status

### ISSUE THREAD

**Issue by avh4** [orderedlist/unity-ui#42]
Other themes show added files in green, and modified files in orange in the file tree, but with unity-ui, those files are undistinguishable from other files.

**Comment by RossBarnie** [comment]
Any changes are shown with a symbol to the right of the file for me.

Unity Dark
![screen shot 2015-01-08 at 09 22 38](https://cloud.githubusercontent.com/assets/2567153/5660436/0ee6154c-9718-11e4-9f12-b094ccd68f54.png)

Unity
![screen shot 2015-01-08 at 09 23 28](https://cloud.githubusercontent.com/assets/2567153/5660441/19601cac-9718-11e4-8eaa-b27774e5976e.png)

**Comment by orderedlist** [comment]
Not using the colors for the filenames is a decision made for this theme. The icons have been added for clarity.
