### ISSUE TITLE
ui-variables.less missing?

### ISSUE THREAD

**Issue by timglorioso** [orderedlist/unity-ui#47]
You're probably aware of this, but from the ["Creating a Theme" guide](https://atom.io/docs/latest/creating-a-theme):
> Interface themes **must** provide a `ui-variables.less` file which contains all of the variables provided by the core themes.

Maybe this information is outdated? Or perhaps you've hidden the file away in that santa hat. Frankly, there's a good chance I'm misunderstanding why it's required, just figured I'd point it out. Thanks for the theme.

**Comment by orderedlist** [comment]
Fixed in v2.0.0
