### ISSUE TITLE
atom-text-editor appears to be missing a font color

### ISSUE THREAD

**Issue by jonnyhaynes** [orderedlist/unity-ui#48]
Since updating to the latest version on Atom 0.166.0 the colour for the text in the <atom-text-editor> field is missing or set to match the background colour? As such nothing shows. See below screen grabs.

*If you look really close there is some copy in there*
![screen shot 2015-01-07 at 15 49 35](https://cloud.githubusercontent.com/assets/1654845/5648334/9cff4c56-9685-11e4-98f9-8f00e014c8d6.png)

*This is more like it should be*
![screen shot 2015-01-07 at 15 49 49](https://cloud.githubusercontent.com/assets/1654845/5648344/b7d4c664-9685-11e4-8bb4-c8a718405eaf.png)

I've noticed this when searching within the file, project or when using emmet.

**Comment by benogle** [comment]
@orderedlist this is likely cause of the shadow DOM enabled by default. You can check this out to get it all updated: https://atom.io/docs/latest/upgrading/upgrading-your-ui-theme
