### ISSUE TITLE
FIX? it seems the last atom update broke unity.

### ISSUE THREAD

**Issue by dengemann** [orderedlist/unity-ui#50]
With Atom 0.168.0 and the last unity-ui version tabs are not displayed at all. Macbook Air 11' and Macbook Pro Retina 15. Both Yosemite.

**Comment by orderedlist** [comment]
Fixed in [1.0.7](https://github.com/orderedlist/unity-ui/releases/tag/v1.0.7)

**Comment by dengemann** [comment]
@orderedlist thanks a lot!
