### ISSUE TITLE
Hides icons in tree view

### ISSUE THREAD

**Issue by dwt** [orderedlist/unity-ui#55]
Hi there,

the themes don't show any icons in the tree view, which makes it much harder to use the outline view than necessary.

![broken unity-ui](https://cloud.githubusercontent.com/assets/57199/6020578/e2648454-abad-11e4-9121-f7cb031876fc.png)
![working standard theme](https://cloud.githubusercontent.com/assets/57199/6020577/e25f7428-abad-11e4-9472-090cf627db72.png)

**Comment by doggan** [comment]
Here's a quick trick to get the file-icons package working with this UI theme:
https://github.com/k9ordon/yosemite-unity-ui/issues/2#issuecomment-46526970
