### ISSUE TITLE
Autocomplete popup is rendered transparent

### ISSUE THREAD

**Issue by doggan** [orderedlist/unity-ui#59]
In the latest release of Unity-UI (2.0.1), popups for autocomplete are rendered transparent and are difficult to read. This problem did not exist in the 1.x release cycle.

![unity](https://cloud.githubusercontent.com/assets/517857/6206679/9b5d6952-b5d2-11e4-8d67-f38209035457.png)

For reference, this is what it looks like in the One Light UI theme:

![one_light](https://cloud.githubusercontent.com/assets/517857/6206682/aa9692cc-b5d2-11e4-88c3-b7516214f41b.png)

**Comment by orderedlist** [comment]
Fixed in 2.0.2. Thanks for the report.
