### ISSUE TITLE
Which syntax theme in the screenshot?

### ISSUE THREAD

**Issue by brendanfalkowski** [orderedlist/unity-ui#61]
I'm using "Base16 Tomorrow Dark" with Source Code Pro typeface @ 14px. Have stuck with this for a long time in Sublime, but type in Atom is very fuzzy with the same.

Curious what you're using the screenshot because the coloration looks similar and fairly crisp.

**Comment by orderedlist** [comment]
It's a retina screenshot, but the Syntax theme is One Dark. Recommended.

**Comment by brendanfalkowski** [comment]
Ah, One Dark looks nice. Hadn't updated Atom for a long time, never saw that's a default syntax choice. Thanks!

Only suggestion for Unity is increasing contrast slightly on the file tabs. Bit hard to tell which is active.
