### ISSUE TITLE
Is there a plan to change the directory icon ?

### ISSUE THREAD

**Issue by agileago** [orderedlist/unity-ui#77]
maybe we can do more native. directory icon use the OS native will be very beautiful . consider it. like [textmate](https://github.com/textmate/textmate)

**Comment by agileago** [comment]
![image](https://cloud.githubusercontent.com/assets/11799110/10123604/58181874-6570-11e5-8384-da8416953f31.png)

like this

**Comment by orderedlist** [comment]
So, there's no way to grab the native file icons using CSS, so I doubt this will happen in a seamless way. Sorry. 😦
