### ISSUE TITLE
Deprecated selector in `unity-ui/index.less`

### ISSUE THREAD

**Issue by DanFreed** [orderedlist/unity-ui#88]
In `unity-ui/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini]::shadow .placeholder-text` => `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini].editor .placeholder-text`

* `atom-text-editor[mini] .selection .region,
atom-text-editor[mini]::shadow .selection .region` => `atom-text-editor[mini] .selection .region,
atom-text-editor[mini].editor .selection .region`

* `atom-text-editor[mini] .cursor,
atom-text-editor[mini]::shadow .cursor` => `atom-text-editor[mini] .cursor,
atom-text-editor[mini].editor .cursor`

* `atom-text-editor[mini].is-focused,
atom-text-editor[mini].is-focused::shadow` => `atom-text-editor[mini].is-focused,
atom-text-editor[mini].is-focused.editor`

* `atom-text-editor[mini].is-focused .selection .region,
atom-text-editor[mini].is-focused::shadow .selection .region` => `atom-text-editor[mini].is-focused .selection .region,
atom-text-editor[mini].is-focused.editor .selection .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by eloypnd** [comment]
I am still getting the same deprecation message:

Atom v1.13.0
unity-ui v2.1.8
Mac OS X El Capitan 10.11.6

**Comment by felixfoertsch** [comment]
This problem is still around.

Atom 1.14.13
unity-ui 2.1.8
macOS 10.12.3

**Comment by nicjar** [comment]
Still around

Atom 1.5.0
unity-ui 2.1.8
macOS 10.12.3
