### ISSUE TITLE
Tab Height Jumps While Dragging

### ISSUE THREAD

**Issue by tsmango** [orderedlist/unity-ui#92]
I've noticed this strange issue where dragging a tab will cause the tab bar height to jump, making it a little tough to complete the drag in certain circumstances. At first I thought this was an Atom specific issue, but after some testing, I'm not seeing the same issue in other themes.

Here's a screen cap:

![2017-01-19 11_30_16](https://cloud.githubusercontent.com/assets/9503/22115371/ac4a8316-de3a-11e6-9b0a-1cba9ff971ef.gif)

**Comment by thisispiers** [comment]
+1 extremely annoying
there are even times where the flickering means that the tab doesn't reorder

**Comment by tsmango** [comment]
🎉 🎉 🎉

**Comment by orderedlist** [comment]
Released in [2.1.10](https://github.com/orderedlist/unity-ui/releases/tag/v2.1.10)
