### ISSUE TITLE
Bottom Right Icons Misaligned

### ISSUE THREAD

**Issue by Gallactide** [orderedlist/unity-ui#94]
I am running El Capitan (10.11.6) and Atom 1.12.9 with Unity-UI 2.1.8.

The Bottom right icons (I.e. Pending updates, current Language etc.) are misaligned, starting from approx. the midpoint of the bottom bar. 

Some UI changes can lead to the alignment to update to the correct position but I haven't figured out what exactly prompts this change.

<img width="105" src="https://cloud.githubusercontent.com/assets/6361508/22215618/52cf0ad6-e19c-11e6-819c-8cef4f2606a9.png">

**Comment by orderedlist** [comment]
I haven't come across this, and am unable to reproduce. Going to close for now, feel free to reopen if we can identify another theme or package that causes this to happen.
